In [407]:
from google.colab import drive
drive.mount('/content/gdrive')

Drive already mounted at /content/gdrive; to attempt to forcibly remount, call drive.mount("/content/gdrive", force_remount=True).


In [408]:
from imutils import paths
import matplotlib.pyplot as plt
import numpy as np
import os
dataset='/content/gdrive/MyDrive/doc_nlp_ass3'

In [409]:
file_paths=[]
for file in os.listdir(dataset):
    # Check whether file is in text format or not
    if file.endswith(".txt"):
        file_path = f"{dataset}/{file}"
        file_paths.append(file_path)


In [410]:
print(file_paths)

['/content/gdrive/MyDrive/doc_nlp_ass3/Ummaya_Mosque.txt', '/content/gdrive/MyDrive/doc_nlp_ass3/Razi.txt', '/content/gdrive/MyDrive/doc_nlp_ass3/Richard_Stallman.txt', '/content/gdrive/MyDrive/doc_nlp_ass3/Nuclear_Power.txt', '/content/gdrive/MyDrive/doc_nlp_ass3/Computer.txt', '/content/gdrive/MyDrive/doc_nlp_ass3/Soccer_Worldcup.txt', '/content/gdrive/MyDrive/doc_nlp_ass3/Portugal_football_team.txt', '/content/gdrive/MyDrive/doc_nlp_ass3/Christiano_Ronaldo.txt', '/content/gdrive/MyDrive/doc_nlp_ass3/Enrico_Fermi.txt', '/content/gdrive/MyDrive/doc_nlp_ass3/Real_Madrid.txt', '/content/gdrive/MyDrive/doc_nlp_ass3/Raul_Gonzales.txt', '/content/gdrive/MyDrive/doc_nlp_ass3/Islamic_History.txt', '/content/gdrive/MyDrive/doc_nlp_ass3/Crusades.txt', '/content/gdrive/MyDrive/doc_nlp_ass3/Light.txt', '/content/gdrive/MyDrive/doc_nlp_ass3/Physics.txt', '/content/gdrive/MyDrive/doc_nlp_ass3/Solaris.txt', '/content/gdrive/MyDrive/doc_nlp_ass3/Atom.txt', '/content/gdrive/MyDrive/doc_nlp_ass3/Inter

In [411]:
def read_text_file(file_path):
  with open(file_path) as f:
      #print(f.read())
      docs_content=f.read()
  return(docs_content)

In [412]:
docs_content=[]
for i in file_paths:
  sss=read_text_file(i)
  docs_content.append(sss)

In [413]:
print(docs_content[0])

الجامع B-LOC
الأموي I-LOC
أو O
المسجد B-LOC
الأموي I-LOC
أو O
جامع B-LOC
بني I-LOC
أمية I-LOC
الكبير I-LOC
مسجد O
في O
دمشق B-LOC
، O
سورية B-LOC
من O
روائع O
الفن O
المعماري O
الإسلامي O
، O
يقع O
في O
قلب O
المدينة O
القديمة O
. O

له O
تاريخ O
حافل O
في O
جميع O
العهود O
والحضارات O
كان O
في O
العهد O
القديم O
سوقا O
، O
ثم O
تحول O
في O
العهد O
الروماني O
إلى O
معبد O
أنشئ O
في O
القرن O
الأول O
الميلادي O
. O

ثم O
تحول O
مع O
الزمن O
إلى O
كنيسة O
. O

ولما O
دخل O
المسلمون B-PER
إلى O
دمشق B-LOC
، O
دخل O
خالد B-PER
بن I-PER
الوليد I-PER
عنوة O
، O
ودخل O
أبو B-PER
عبيدة I-PER
بن I-PER
الجراح I-PER
صلحا O
. O

فصار O
نصفه O
مسجد O
ونصفه O
كنيسة O
. O

ثم O
قام O
الخليفة O
الأموي O
الوليد B-PER
بن I-PER
عبد I-PER
الملك I-PER
سنة O
96ه O
( O
الموافق O
ل O
) O
بتحويل O
الكنيسة O
إلى O
مسجد O
، O
وأعاد O
بناءه O
من O
جديد O
، O
وكساه O
وزينه O
بالفسيفساء O
والمنمنمات O
والنقوش O
وأفضل O
ما O
زينت O
به O
المساجد O
في O
تاريخ O
الإسلام O
. O

وفي O
المسجد B-LOC
الأموي I-LOC
أول O
مئذن

In [414]:
# Setup
!pip install -q wordcloud
import wordcloud

import nltk
nltk.download('stopwords')
nltk.download('wordnet')
nltk.download('punkt')
nltk.download('averaged_perceptron_tagger')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /root/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!


True

In [415]:
import numpy as np
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
import bs4 as bs
import urllib.request
import re
import nltk
def processing(doc1):
  processed_article = re.sub('[^ا-يءةآإاًؤأئ]', ' ', doc1 )
  processed_article = re.sub(r'\s+', ' ', processed_article)
  all_sentences = nltk.sent_tokenize(processed_article)
  words = [nltk.word_tokenize(sent) for sent in all_sentences]
  return (words[0]) 

In [416]:
docs_words=[]
for i in docs_content:
  doc=processing(i)
  docs_words.append(doc)


In [417]:
print(len(docs_words))

28


In [418]:
print(docs_words[27])

['مسجد', 'ابن', 'طولون', 'هو', 'مسجد', 'أقامه', 'أحمد', 'بن', 'طولون', 'عام', 'ه', 'أنفق', 'أحمد', 'بن', 'طولون', 'ألف', 'دينار', 'في', 'بنائه', 'وقد', 'اهتم', 'بالأمور', 'الهندسية', 'في', 'بناء', 'المسجد', 'مئذنة', 'المسجد', 'هي', 'أقدم', 'مئذنة', 'موجودة', 'في', 'مصر', 'يعد', 'مسجد', 'ابن', 'طولون', 'المسجد', 'الوحيد', 'بمصر', 'الذى', 'غلب', 'عليه', 'طراز', 'سامراء', 'حيث', 'المئذنة', 'الملوية', 'المدرجة', 'قام', 'السلطان', 'لاجين', 'بإدخال', 'بعض', 'الإصلاحات', 'فيه', 'وعين', 'لذلك', 'مجموعة', 'من', 'الصناع', 'كما', 'أمر', 'بصناعة', 'ساعة', 'فيه', 'فجعلت', 'قبة', 'فيها', 'طيقان', 'صغيرة', 'على', 'عدد', 'ساعات', 'الليل', 'والنهار', 'وفتحة', 'فإذا', 'مرت', 'ساعة', 'انغلقت', 'الطاقة', 'التي', 'هي', 'لتلك', 'الساعة', 'وهكذا', 'ثم', 'تعود', 'كل', 'مرة', 'ثانية', 'وفي', 'عهد', 'الأيوبيين', 'أصبح', 'جامع', 'ابن', 'طولون', 'جامعة', 'تدرس', 'فيه', 'المذاهب', 'الفقهية', 'الأربعة', 'وكذلك', 'الحديث', 'والطب', 'إلى', 'جانب', 'تعليم', 'الأيتام', 'طولون', 'هو', 'أحد', 'المماليك', 'الأتراك', 'الذي

In [419]:
docss=np.concatenate(docs_words,axis=0)

In [420]:
print(docss)

['الجامع' 'الأموي' 'أو' ... 'الخاصة' 'بآثار' 'القاهرة']


In [421]:
print(len(docss))

63605


In [422]:
pieces = 1000
allsentence = np.array_split(docss, pieces)
print(allsentence)

[array(['الجامع', 'الأموي', 'أو', 'المسجد', 'الأموي', 'أو', 'جامع', 'بني',
       'أمية', 'الكبير', 'مسجد', 'في', 'دمشق', 'سورية', 'من', 'روائع',
       'الفن', 'المعماري', 'الإسلامي', 'يقع', 'في', 'قلب', 'المدينة',
       'القديمة', 'له', 'تاريخ', 'حافل', 'في', 'جميع', 'العهود',
       'والحضارات', 'كان', 'في', 'العهد', 'القديم', 'سوقا', 'ثم', 'تحول',
       'في', 'العهد', 'الروماني', 'إلى', 'معبد', 'أنشئ', 'في', 'القرن',
       'الأول', 'الميلادي', 'ثم', 'تحول', 'مع', 'الزمن', 'إلى', 'كنيسة',
       'ولما', 'دخل', 'المسلمون', 'إلى', 'دمشق', 'دخل', 'خالد', 'بن',
       'الوليد', 'عنوة'], dtype='<U20'), array(['ودخل', 'أبو', 'عبيدة', 'بن', 'الجراح', 'صلحا', 'فصار', 'نصفه',
       'مسجد', 'ونصفه', 'كنيسة', 'ثم', 'قام', 'الخليفة', 'الأموي',
       'الوليد', 'بن', 'عبد', 'الملك', 'سنة', 'ه', 'الموافق', 'ل',
       'بتحويل', 'الكنيسة', 'إلى', 'مسجد', 'وأعاد', 'بناءه', 'من', 'جديد',
       'وكساه', 'وزينه', 'بالفسيفساء', 'والمنمنمات', 'والنقوش', 'وأفضل',
       'ما', 'زينت', 'به', 'المساجد'

In [423]:
def listToString(s): 
    
    # initialize an empty string
    str1 = " " 
    
    # return string  
    return (str1.join(s))

In [424]:
all_sentances=[]
for i in allsentence:
  sentance=listToString(i)
  all_sentances.append(sentance)


In [426]:
print(all_sentances[1])

ودخل أبو عبيدة بن الجراح صلحا فصار نصفه مسجد ونصفه كنيسة ثم قام الخليفة الأموي الوليد بن عبد الملك سنة ه الموافق ل بتحويل الكنيسة إلى مسجد وأعاد بناءه من جديد وكساه وزينه بالفسيفساء والمنمنمات والنقوش وأفضل ما زينت به المساجد في تاريخ الإسلام وفي المسجد الأموي أول مئذنة في الإسلام المسماة مئذنة العروس وله اليوم ثلاث مآذن وأربع أبواب وقبة كبيرة قبة النسر


In [427]:
from keras.preprocessing.text import Tokenizer
# prepare tokenizer
t = Tokenizer()
t.fit_on_texts(all_sentances)
vocab_size = len(t.word_index) + 1
# integer encode the documents
encoded_docs = t.texts_to_sequences(all_sentances)
print('encoded_docs:\n',encoded_docs)

encoded_docs:
 [[86, 303, 8, 289, 303, 8, 304, 401, 1077, 290, 521, 1, 34, 1729, 2, 3982, 2794, 2795, 200, 562, 1, 485, 110, 221, 90, 191, 2796, 1, 157, 2797, 3983, 9, 1, 682, 683, 3984, 47, 1246, 1, 682, 1247, 5, 1437, 1730, 1, 58, 104, 1078, 47, 1246, 12, 1079, 5, 837, 1080, 1081, 563, 5, 34, 1081, 1248, 30, 747, 6414], [3985, 684, 3986, 30, 3987, 6415, 6416, 6417, 521, 6418, 837, 47, 65, 250, 303, 747, 30, 165, 215, 38, 133, 6419, 615, 2798, 748, 5, 521, 6420, 3988, 2, 375, 6421, 3989, 1731, 6422, 1732, 6423, 15, 3990, 81, 2155, 1, 191, 187, 28, 289, 303, 53, 1082, 1, 187, 2799, 1082, 2800, 1083, 206, 402, 1733, 2801, 685, 6424, 177, 262, 1734], [6425, 6426, 1, 6427, 6428, 3991, 1735, 945, 1735, 6429, 1735, 231, 1735, 6430, 1736, 6431, 946, 2, 1438, 6432, 1249, 1, 3992, 2802, 2156, 2157, 3993, 126, 6433, 3994, 2803, 1084, 232, 2158, 6434, 305, 192, 2, 6435, 6436, 2804, 6437, 187, 37, 2805, 120, 222, 6438, 1, 191, 187, 6439, 1085, 178, 2, 2159, 2806, 6440, 6441, 6442, 3995, 2807, 216

In [428]:
d=[]
for i in encoded_docs:
  d.append(len(i))

In [429]:
max_size = max(d)
print(max_size)

64


In [430]:
print(d)

[64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64,

In [431]:
#pad documents to a max length of 1075 words
from keras.preprocessing.sequence import pad_sequences
max_length = max_size
padded_docs = pad_sequences(encoded_docs, maxlen=max_length, padding='post')
print('padded_docs:\n',padded_docs)

padded_docs:
 [[   86   303     8 ...    30   747  6414]
 [ 3985   684  3986 ...   177   262  1734]
 [ 6425  6426     1 ...  2807   216    75]
 ...
 [ 1756   317    30 ...     1  1699     0]
 [ 2154  6404    75 ...   207  6413     0]
 [16627 16628    38 ... 16643   943     0]]


In [432]:
def getlabels(doc1):
  processed_article = re.sub('[^A-Z]', ' ', doc1 )
  processed_article = re.sub(r'\s+', ' ', processed_article)
  lb = nltk.sent_tokenize(processed_article)
  lab = [nltk.word_tokenize(sent) for sent in lb]
  print(lab)
  labels=[]
  for i in range(len(lab)):
    for j in range(len(lab[i])):
      if (lab[i][j]=="LOC"):
        labels.append(lab[i][j])
      elif(lab[i][j]=="MIS"):
        labels.append(lab[i][j])
      elif(lab[i][j]=="PER"):
        labels.append(lab[i][j])
      elif(lab[i][j]=="ORG"):
        labels.append(lab[i][j])
      elif(lab[i][j]=="O"):
        labels.append(lab[i][j])
  
  return(labels)

In [433]:
doc_labels=[]
for i in docs_content:
  doc11=getlabels(i)
  ddd=np.array(doc11)
  doc_labels.append(ddd)

[['B', 'LOC', 'I', 'LOC', 'O', 'B', 'LOC', 'I', 'LOC', 'O', 'B', 'LOC', 'I', 'LOC', 'I', 'LOC', 'I', 'LOC', 'O', 'O', 'B', 'LOC', 'O', 'B', 'LOC', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'B', 'PER', 'O', 'B', 'LOC', 'O', 'O', 'B', 'PER', 'I', 'PER', 'I', 'PER', 'O', 'O', 'O', 'B', 'PER', 'I', 'PER', 'I', 'PER', 'I', 'PER', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'B', 'PER', 'I', 'PER', 'I', 'PER', 'I', 'PER', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'B', 'LOC', 'I', 'LOC', 'O', 'O', 'O', 'O', 'O', 'B', 'LOC', 'I', 'LOC', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'B', 'PER', 'O', 'B', 'PER', 'O', 'B', 'PER', 'O', 'B', 'PE

In [434]:
la=np.array(doc_labels)
print(la)

[array(['LOC', 'LOC', 'O', ..., 'O', 'O', 'O'], dtype='<U3')
 array(['PER', 'PER', 'PER', ..., 'O', 'O', 'O'], dtype='<U3')
 array(['PER', 'PER', 'O', ..., 'O', 'O', 'O'], dtype='<U3')
 array(['O', 'O', 'O', ..., 'O', 'O', 'O'], dtype='<U3')
 array(['O', 'O', 'O', ..., 'O', 'O', 'O'], dtype='<U3')
 array(['O', 'O', 'O', ..., 'O', 'O', 'ORG'], dtype='<U3')
 array(['ORG', 'ORG', 'O', ..., 'O', 'O', 'LOC'], dtype='<U3')
 array(['PER', 'PER', 'O', ..., 'O', 'O', 'O'], dtype='<U3')
 array(['PER', 'PER', 'O', ..., 'O', 'O', 'O'], dtype='<U3')
 array(['ORG', 'ORG', 'O', ..., 'O', 'O', 'O'], dtype='<U3')
 array(['PER', 'PER', 'O', ..., 'O', 'O', 'O'], dtype='<U3')
 array(['O', 'O', 'O', ..., 'LOC', 'O', 'O'], dtype='<U3')
 array(['MIS', 'MIS', 'O', ..., 'O', 'O', 'O'], dtype='<U3')
 array(['O', 'O', 'MIS', ..., 'O', 'O', 'O'], dtype='<U3')
 array(['MIS', 'O', 'O', ..., 'O', 'O', 'O'], dtype='<U3')
 array(['O', 'O', 'O', ..., 'O', 'O', 'O'], dtype='<U3')
 array(['O', 'O', 'O', ..., 'O', 'O', 'O

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  """Entry point for launching an IPython kernel.


In [435]:
laa=np.concatenate(la,axis=0)

In [436]:
print(len(laa))

73894


In [437]:
print(np.unique(laa))

['LOC' 'MIS' 'O' 'ORG' 'PER']


In [438]:
pieces = 1000
alllabels= np.array_split(laa, pieces)
print(alllabels)


[array(['LOC', 'LOC', 'O', 'LOC', 'LOC', 'O', 'LOC', 'LOC', 'LOC', 'LOC',
       'O', 'O', 'LOC', 'O', 'LOC', 'O', 'O', 'O', 'O', 'O', 'O', 'O',
       'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O',
       'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O',
       'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O',
       'O', 'PER', 'O', 'LOC', 'O', 'O', 'PER', 'PER', 'PER', 'O', 'O',
       'O', 'PER'], dtype='<U3'), array(['PER', 'PER', 'PER', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O',
       'O', 'O', 'O', 'PER', 'PER', 'PER', 'PER', 'O', 'O', 'O', 'O', 'O',
       'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O',
       'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O',
       'LOC', 'LOC', 'O', 'O', 'O', 'O', 'O', 'LOC', 'LOC', 'O', 'O', 'O',
       'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O'],
      dtype='<U3'), array(['O', 'O', 'PER', 'O', 'PER', 'O', 'PER', 'O', 'PER', 'O', 'O', 'O',
   

In [439]:
all_labels=[]
for i in alllabels:
  labelsentance=listToString(i)
  all_labels.append(labelsentance)

In [440]:
print(all_labels)

['LOC LOC O LOC LOC O LOC LOC LOC LOC O O LOC O LOC O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O PER O LOC O O PER PER PER O O O PER', 'PER PER PER O O O O O O O O O O O O PER PER PER PER O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O LOC LOC O O O O O LOC LOC O O O O O O O O O O O O O O O', 'O O PER O PER O PER O PER O O O O O O O O O O O O PER O O O O O PER PER PER O O O O O O O O O O O O O O O O O O O O O O O O O O O O O PER O O O O O O O LOC O O O LOC O O', 'O O O O O O PER PER PER O O O O O O O O O O O O O O LOC LOC O O O O O O O O O LOC O O O O O O O LOC LOC O O O O O O O O O LOC O O O O O O O O O O O O O O PER O O O LOC LOC', 'O LOC O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O PER O LOC O O O O O O O O O O O O O O LOC LOC LOC O O O O O O O O O', 'O O O O O O O O O O O O O O PER PER O O O O O O O O O O O O LOC LOC O O O O O O O O O O O O O O O O O O PER PER O O O O O O O O LOC

In [441]:
from sklearn.preprocessing import LabelBinarizer
labels = np.array(all_labels)
# perform one-hot encoding on the labels
lb = LabelBinarizer()
labels = lb.fit_transform(labels)

In [442]:
print(labels)

[[1 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [472]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(padded_docs, labels, test_size=0.2, random_state=42)

In [473]:
print(X_train.shape, X_test.shape, y_train.shape, y_test.shape)

(800, 64) (200, 64) (800, 921) (200, 921)


In [474]:
from gensim.models import KeyedVectors
# Load vectors directly from the file
model = KeyedVectors.load_word2vec_format('/content/gdrive/MyDrive/model.bin', binary=True)

In [475]:
w2v_embeddings_index={}
for word in model.wv.vocab:
  w2v_embeddings_index[word] = model[word]
print('Loaded %s word vectors.'% len(w2v_embeddings_index))

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: DeprecationWarning: Call to deprecated `wv` (Attribute will be removed in 4.0.0, use self instead).
  


Loaded 1071056 word vectors.


In [476]:
# create a weight matrix for words in training docs
embedding_matrix = np.zeros((vocab_size, 100))
for word, i in t.word_index.items():
    embedding_vector = w2v_embeddings_index.get(word)
    if embedding_vector is not None:
        embedding_matrix[i] = embedding_vector
print("Embedding Matrix shape:", embedding_matrix.shape)

Embedding Matrix shape: (16644, 100)


In [477]:
import tensorflow as tf
embedding_layer = tf.keras.layers.Embedding(vocab_size, 100, weights=[embedding_matrix], input_length=64, trainable=False)

In [480]:
# define model
input_placeholder= tf.keras.Input(shape=(64,), dtype='int32')
input_embedding = embedding_layer(input_placeholder)
lstm= tf.keras.layers.LSTM(units=20, activation='relu')(input_embedding)
preds = tf.keras.layers.Dense(921, activation='sigmoid', name = "activation")(lstm)
modellstm = tf.keras.models.Model(inputs=input_placeholder, outputs=preds)
# compile the model
modellstm.compile(loss='binary_crossentropy', optimizer=tf.keras.optimizers.Adam(lr=0.001), metrics=['accuracy'])
# summarize the model
print(modellstm.summary())
print('\n # Fit model on training data')
# fit the model
history= modellstm.fit(X_train, y_train, epochs=1000)

Model: "model_15"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_16 (InputLayer)       [(None, 64)]              0         
                                                                 
 embedding_9 (Embedding)     multiple                  1664400   
                                                                 
 lstm_15 (LSTM)              (None, 20)                9680      
                                                                 
 activation (Dense)          (None, 921)               19341     
                                                                 
Total params: 1,693,421
Trainable params: 29,021
Non-trainable params: 1,664,400
_________________________________________________________________
None

 # Fit model on training data
Epoch 1/1000


/usr/local/lib/python3.7/dist-packages/keras/optimizer_v2/adam.py:105: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  super(Adam, self).__init__(name, **kwargs)


25/25 [==============================] - 2s 51ms/step - loss: 0.6740 - accuracy: 0.0012
Epoch 2/1000
25/25 [==============================] - 1s 51ms/step - loss: 0.8192 - accuracy: 0.0000e+00
Epoch 3/1000
25/25 [==============================] - 1s 50ms/step - loss: 0.5911 - accuracy: 0.0000e+00
Epoch 4/1000
25/25 [==============================] - 1s 49ms/step - loss: 0.5638 - accuracy: 0.0000e+00
Epoch 5/1000
25/25 [==============================] - 1s 48ms/step - loss: 0.5368 - accuracy: 0.0000e+00
Epoch 6/1000
25/25 [==============================] - 1s 48ms/step - loss: 0.5110 - accuracy: 0.0000e+00
Epoch 7/1000
25/25 [==============================] - 1s 49ms/step - loss: 0.4866 - accuracy: 0.0000e+00
Epoch 8/1000
25/25 [==============================] - 1s 48ms/step - loss: 0.4635 - accuracy: 0.0000e+00
Epoch 9/1000
25/25 [==============================] - 1s 49ms/step - loss: 0.4417 - accuracy: 0.0000e+00
Epoch 10/1000
25/25 [==============================] - 1s 48ms/step - lo

In [481]:
# evaluate the model
loss, accuracy = modellstm.evaluate(X_train, y_train, verbose=0)
print('Accuracy: %f' % (accuracy*100))

Accuracy: 94.125003


In [482]:
from nltk.corpus.reader import string_category
from keras.preprocessing.text import Tokenizer
text=['عمرو يعيش في القاهره منذ زمن مع احمد صديقة']
t = Tokenizer()
t.fit_on_texts(text)
encoded_text = t.texts_to_sequences(text)
print('encoded_text:\n',encoded_text)
padded_text = pad_sequences(encoded_text, maxlen=max_length, padding='post')
print('padded_text:\n',padded_text)
pred=modellstm.predict(padded_text)
i = np.argmax(pred)
label = lb.classes_[i]
text11 = "PREDICTION: {}".format(label.upper())
print(text11)

encoded_text:
 [[1, 2, 3, 4, 5, 6, 7, 8, 9]]
padded_text:
 [[1 2 3 4 5 6 7 8 9 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]]
PREDICTION: O O O O O O O O O O O MIS O O O MIS O O O O O O O O O O O O O O O O O O O MIS O O O MIS O O O O O MIS O O O O O O O O ORG O ORG O ORG O ORG ORG ORG O O O MIS O O O O O MIS O
